version: '3.1'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 4000:3306
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: criminal
  mongo:
    image: mongo
    restart: always
    volumes:
      - "./datamongo:/data/db"
    ports:
      - 27017:27017
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8484:80
    environment:
      PMA_PASSWORD: 1234
      PMA_USER: root
      PMA_HOSTS: mysql
